### ISSUE TITLE
Is problem solved?

### ISSUE THREAD

**Issue by Uterr** [ClemensSchneider/angular-buildoptimizer-bug#1]
Hi! I also having error in my application when compiling it with buildOptimizer flag. Is fix for this bug found jr is it more complex?

**Comment by ClemensSchneider** [comment]
Hi, to my knowledge, the issue has not been fixed on Angular side (at least for V7). The work-around was to simply disable build optimization and live with the potentially bigger bundles :/

See https://github.com/angular/angular/issues/28179 for reference.
